language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.* # Does not work with php below 5.5

before_script:
  - pecl install pecl_http
  - composer require --prefer-source --dev symfony/event-dispatcher:${SYMFONY_VERSION}

script: vendor/bin/phpunit -c phpunit.xml.travis -v

after_success:
  - travis_retry php vendor/bin/coveralls -v

matrix:
  exclude:
      - php: 5.3
        env: SYMFONY_VERSION=3.0.*
      - php: 5.4
        env: SYMFONY_VERSION=3.0.*
  allow_failures:
      - php: 5.3
      - php: nightly

sudo: false
